[project]
name = "mega-safe"
authors = ["MegaSafe Team"]
description = "Secure digital asset protection and risk management platform"
telemetry = false
requirements = []

[contracts.identity-vault]
path = "contracts/identity-vault.clar"
depends_on = []

[contracts.risk-monitor]
path = "contracts/risk-monitor.clar"
depends_on = []

[contracts.verification-gateway]
path = "contracts/verification-gateway.clar"
depends_on = []

[contracts.security-incentive]
path = "contracts/security-incentive.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
